# Generated by Django 2.0.13 on 2020-01-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Учебный предмет')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='practice.PracticeCategory', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='Текста задачи')),
                ('complexity', models.CharField(max_length=50, verbose_name='Сложность задачи')),
                ('type_task', models.CharField(max_length=50, verbose_name='Тип задачи')),
                ('practicecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeCategory', verbose_name='Практический материал')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeTaskVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicetask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeTask', verbose_name='Класс задачи')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeType',
            fields=[
                ('article', models.AutoField(primary_key=True, serialize=False, verbose_name='Тип задачи')),
            ],
        ),
    ]
