# Generated by Django 2.0.13 on 2020-02-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('courses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Учебный предмет')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='practice.PracticeCategory', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='Текста задачи')),
                ('complexity', models.CharField(max_length=50, verbose_name='Сложность задачи')),
                ('type_task', models.CharField(max_length=50, verbose_name='Тип задачи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeCategory', verbose_name='Практический материал')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Correct'), ('P', 'Partially correct'), ('W', 'Wrong')], max_length=1, verbose_name='Статус ответа')),
                ('tries_count', models.IntegerField(default=0, verbose_name='Чило попыток')),
                ('user_answer', models.CharField(max_length=50, verbose_name='Ответ пользователя')),
                ('correct_answer', models.CharField(max_length=50, verbose_name='Правильный ответ')),
                ('params', models.CharField(max_length=50, verbose_name='')),
                ('practicetask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeTask', verbose_name='Практическое задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='practicetask',
            name='student',
            field=models.ManyToManyField(through='practice.TaskUserData', to='users.Student'),
        ),
    ]
