# Generated by Django 2.0.13 on 2020-01-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicecategory',
            old_name='id_practicetask',
            new_name='practicetask',
        ),
        migrations.RenameField(
            model_name='practicecategory',
            old_name='id_studysubject',
            new_name='studysubject',
        ),
        migrations.RenameField(
            model_name='practicetaskvariation',
            old_name='id_practicetask',
            new_name='practicetask',
        ),
        migrations.RenameField(
            model_name='practicetype',
            old_name='article_id',
            new_name='article',
        ),
    ]
