# Generated by Django 2.2 on 2020-03-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicetask',
            name='task_type',
        ),
    ]
