# Generated by Django 2.0.13 on 2020-01-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200121_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicecategory',
            name='practicetask',
        ),
        migrations.AddField(
            model_name='practicetask',
            name='practicecategory',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeCategory'),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='complexity',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='content',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='type_task',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
