# Generated by Django 2.2 on 2020-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_practicetask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetask',
            name='task_type',
            field=models.CharField(choices=[(1, 'Тестовая'), (2, 'Самообучение'), (3, 'Контролирующая')], default=1, max_length=50, verbose_name='Тип задачи'),
        ),
    ]
