# Generated by Django 2.0.13 on 2020-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20200121_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetask',
            name='complexity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='type_task',
            field=models.CharField(max_length=50),
        ),
    ]
