# Generated by Django 2.0.13 on 2020-01-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_auto_20200121_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicecategory',
            old_name='studysubject',
            new_name='course',
        ),
    ]
