# Generated by Django 2.0.13 on 2020-02-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200208_0919'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='practicetask',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeTask', verbose_name='Задача'),
        ),
    ]
