# Generated by Django 2.0.13 on 2020-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=1),
        ),
    ]
