# Generated by Django 2.0.13 on 2020-02-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprogress_practicetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='practicetask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeTask', verbose_name='Задача'),
        ),
    ]
