# Generated by Django 2.0.13 on 2020-01-21 15:04

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200120_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_user',
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='id_practicetask',
            new_name='practicetask',
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='id_student',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='id_teacher',
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
