# Generated by Django 2.0.13 on 2020-02-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200208_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='available_subjects',
            field=models.ManyToManyField(blank=True, related_name='_group_available_subjects_+', to='users.Group', verbose_name='Доступные предметы'),
        ),
    ]
