# Generated by Django 2.0.13 on 2020-01-21 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200121_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_subjects', models.ManyToManyField(related_name='_course_available_subjects_+', to='users.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='available_subjects',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
    ]
