# Generated by Django 2.0.13 on 2020-01-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_reviewsonteacher_usercomplaints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComplaints',
            new_name='UserComplaint',
        ),
    ]
