# Generated by Django 2.0.13 on 2020-01-21 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200121_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='available_subjects',
            field=models.ManyToManyField(related_name='_course_available_subjects_+', to='users.Course', verbose_name='Доступные предметы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
