# Generated by Django 2.0.13 on 2020-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200127_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsonteacher',
            name='reviews',
            field=models.TextField(default='Отзыв', verbose_name='Отзывы на преподавателей'),
        ),
    ]
