# Generated by Django 2.0.13 on 2020-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200121_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answers',
            field=models.CharField(default='kek', max_length=100, verbose_name='Ответы'),
        ),
    ]
