# Generated by Django 2.0.13 on 2020-01-21 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название курса')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('available_subjects', models.ManyToManyField(related_name='_studygroup_available_subjects_+', to='users.StudyGroup', verbose_name='Доступные предметы')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='available_subjects',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
