# Generated by Django 2.0.13 on 2020-01-21 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200121_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название курса')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('available_subjects', models.ManyToManyField(related_name='_group_available_subjects_+', to='users.Group', verbose_name='Доступные предметы')),
            ],
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='available_subjects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='studygroup',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='users.Group'),
        ),
    ]
