# Generated by Django 2.0.13 on 2020-01-21 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200121_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ForeignKey(default='some strings', on_delete=django.db.models.deletion.CASCADE, related_name='Student_course', to='users.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(default='some strings', on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_course', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='users.Group'),
        ),
    ]
