# Generated by Django 2.0.13 on 2020-01-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theorycategory',
            old_name='id_studysubject',
            new_name='studysubject',
        ),
        migrations.RenameField(
            model_name='theorycategory',
            old_name='id_theorypost',
            new_name='theorypost',
        ),
        migrations.RenameField(
            model_name='theorypost',
            old_name='id_studysubject',
            new_name='studysubject',
        ),
    ]
