# Generated by Django 2.0.13 on 2020-01-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_auto_20200127_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theorypost',
            old_name='theorycategory',
            new_name='category',
        ),
    ]
