# Generated by Django 2.0.13 on 2020-01-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_auto_20200121_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysubject',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='theorycategory',
            name='studysubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.StudySubject', verbose_name='Учебный предмет'),
        ),
        migrations.AlterField(
            model_name='theorycategory',
            name='theorypost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.TheoryPost', verbose_name='Теоретический материал'),
        ),
        migrations.AlterField(
            model_name='theorypost',
            name='content',
            field=models.CharField(max_length=50, verbose_name='Аттрибут текста материала'),
        ),
        migrations.AlterField(
            model_name='theorypost',
            name='studysubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.StudySubject', verbose_name='Учебный предмет'),
        ),
    ]
