# Generated by Django 2.0.13 on 2020-01-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_auto_20200121_1902'),
        ('theory', '0003_auto_20200121_1850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudySubject',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='theorycategory',
            old_name='studysubject',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='theorypost',
            old_name='studysubject',
            new_name='course',
        ),
    ]
